FFWEB-2132: Remove category filters
FACT-Finder-Web-Components/magento2-module pull request #336
Opened 2021-08-17 13:05 UTC by paulfcdd

- Solves issue:
FFWEB-2131
 
- Description: 
Remove category filters

- Tested with Magento editions/versions: 
2.4.2

- Tested with PHP versions: 
7.4.20

2021-08-20 05:09 UTC, a-laurowski commented on src/view/frontend/templates/category/remove_category_filter_callback.phtml
> +        });
This is fine but have one flaw, it will not work with the versions other than NG v4
we have to cover also NG v3 an 7.3

2021-08-20 05:09 UTC, a-laurowski requested changes
Missing changelog & incompatibility with older versions of FACT-Finder

2021-09-29 14:32 UTC, paulfcdd commented on src/view/frontend/templates/category/remove_category_filter_callback.phtml
> +        });
it works fine with ng4 usings __associatedFieldNameV4 param, and I have add check for version 7.3

2021-09-30 04:55 UTC, a-laurowski approved these changes, later dismissed
good

2021-10-01 09:23 UTC, a-laurowski approved these changes

2021-10-01 09:23 UTC, a-laurowski commented on src/view/frontend/templates/category/remove_category_filter_callback.phtml
> +                asnData.forEach(function (asnDataElement) {
`asnDataElement` here is in WK terminology `asnGroup`
and `asnGroup` contains elements

2021-10-01 09:23 UTC, a-laurowski commented on src/view/frontend/templates/category/remove_category_filter_callback.phtml
> +                let associatedFieldName = ff.factfinder.communication.Util.extractCategoryPathFieldName();
since it is not changed it can be const

2021-10-01 09:23 UTC, a-laurowski commented on src/view/frontend/templates/category/remove_category_filter_callback.phtml
> +                asnData.forEach(function (asnDataElement) {
asnData.splice(asnData.findIndex(function(group) {
                    group.elements.every(function(element) {
                        return element.associatedFieldName === associatedFieldName;
                    });
                }), 1);

This will remove mutating the array which you iterate through in forEach

2021-10-01 09:23 UTC, a-laurowski commented on src/view/frontend/templates/category/remove_category_filter_callback.phtml
> +                asnData.splice(asnData.findIndex(element=>element.__associatedFieldNameV4 === '<?= $block->getData('category_path_field_name')?>'), 1)
this needs to be changed unfortunately. Since js code is not transpilled, using arrow function will throw an error on IE11 :/

2021-10-01 09:24 UTC, merged