FFWEB-2341: Handle boolean values in getValueOrEmptyString
FACT-Finder-Web-Components/magento2-module pull request #367
Opened 2021-12-14 11:59 UTC by paulfcdd

- Solves issue: 
https://jira.omikron.net/browse/FFWEB-2341

- Description: 
Make this function takes any type of value

- Tested with Magento editions/versions: 
2.4.2

- Tested with PHP versions: 
7.4.20

2021-12-21 12:17 UTC, a-laurowski requested changes

2021-12-21 12:17 UTC, a-laurowski commented on src/Test/Unit/Model/Export/Catalog/ProductType/ConfigurableDataProviderTest.php
> +        $this->repositoryMock->method('get')->willReturnMap(
since you are testing private method `getValueOrEmptyString` this is redundant and can be removed

2021-12-21 12:49 UTC, a-laurowski commented on src/Test/Unit/Model/Export/Catalog/ProductType/ConfigurableDataProviderTest.php
> +        $this->assertEquals($getValueOrEmptyStringMethod, '');
This is the `assertEquals` signature
`  public static function assertEquals($expected, $actual, string $message = ''): void`

so the expected and actual values are misplaced

2021-12-21 12:53 UTC, a-laurowski requested changes
can we also remove the checking from this line 
`   $res[$this->getValueOrEmptyString($sku)][] ` ?
Since this is a key of an associative array, there is no possibility that it will be `false` or `null`

2021-12-21 13:28 UTC, paulfcdd commented
> can we also remove the checking from this line src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php:90 ` $res[$this->getValueOrEmptyString($sku)][]` ? Since this is a key of an associative array, there is no possibility that it will be `false` or `null`

fixed it

2022-01-10 06:17 UTC, a-laurowski requested changes

2022-01-10 06:17 UTC, a-laurowski commented on src/Model/Export/Catalog/ProductType/ConfigurableDataProvider.php
> +    private const ALLOWED_TYPES = ['string', 'integer'];
![image](https://user-images.githubusercontent.com/4511883/148724904-0c37fc41-ec5c-4415-8714-e15eb974d00c.png)
as we discussed before holidays, there are only strings or false value available here (excluding any customizations) so there is no need for introducing ALLOWED_TYPES

2022-01-12 12:55 UTC, a-laurowski approved these changes

2022-01-12 12:58 UTC, merged