FFWEB-2355: convert all class memebers to static typed
FACT-Finder-Web-Components/magento2-module pull request #369
Opened 2022-01-04 13:00 UTC by paulfcdd

- Solves issue: 
FFWEB-2350

- Description: 
convert all class memebers to static typed

- Tested with Magento editions/versions: 
2.4.2

- Tested with PHP versions: 
7.4.20

2022-01-10 14:12 UTC, a-laurowski requested changes

2022-01-10 14:12 UTC, a-laurowski commented on src/Model/Ssr/Template/Engine.php
> +    private Mustache_Engine $engine;
can we do?
`use Mustache_Engine  as Mustache;`

and then 
`private Mustache $engine`

2022-01-10 14:13 UTC, a-laurowski commented
I guess if you use 7.4 syntax you should remove 7.3 from the CI

2022-01-11 10:58 UTC, paulfcdd commented on src/Model/Ssr/Template/Engine.php
> +    private Mustache_Engine $engine;
done

2022-01-11 11:01 UTC, paulfcdd commented
> I guess if you use 7.4 syntax you should remove 7.3 from the CI

There is a separate task for it - FFWEB-2361. Or you suggest to do it in this task?

2022-01-13 06:50 UTC, a-laurowski commented
> > I guess if you use 7.4 syntax you should remove 7.3 from the CI
> 
> There is a separate task for it - FFWEB-2361. Or you suggest to do it in this task?

no, if it's in separate task, then let's ignore CI failure for now

2022-01-13 06:51 UTC, a-laurowski approved these changes

2022-01-13 08:30 UTC, merged