FFWEB-2356: Add arrow_functions
FACT-Finder-Web-Components/magento2-module pull request #371
Opened 2022-01-05 13:12 UTC by paulfcdd

- Solves issue: 
https://jira.omikron.net/browse/FFWEB-2356

- Description: 
Convert of lambda functions to be an arrow function

- Tested with Magento editions/versions: 
2.4.2

- Tested with PHP versions: 
7.4.20

2022-01-10 14:14 UTC, a-laurowski commented on src/Controller/Adminhtml/TestConnection/TestFtpConnection.php
> +        return array_combine(array_map(fn(string $key) => (string)str_replace($prefix, '', $key), array_keys($filtered)), array_values($filtered));
```suggestion
        return array_combine(array_map(fn(string $key) => (string) str_replace($prefix, '', $key), array_keys($filtered)), array_values($filtered));
```

2022-01-10 14:17 UTC, a-laurowski commented on src/ViewModel/CategoryPath.php
>          );
this bracket could be moved to line 84, no ?

2022-01-10 14:18 UTC, a-laurowski commented on src/ViewModel/CategoryPath.php
> +        usort($categories, fn(Category $a, Category $b) => $a->getLevel() - $b->getLevel());
missing returned type

2022-01-10 14:22 UTC, a-laurowski requested changes
sometimes we have
`fn ($args)`
and sometimes
`fn($args)`
please unify this.

What's more the arrow functions in many cases (if not all) don't contain returned type

2022-01-11 11:29 UTC, paulfcdd commented on src/ViewModel/CategoryPath.php
>          );
done

2022-01-13 06:57 UTC, a-laurowski commented
> sometimes we have `fn ($args)` and sometimes `fn($args)` please unify this.
> 
> What's more the arrow functions in many cases (if not all) don't contain returned type

I was looking for some PSR telling how to format the arrow function and i think we follow the closures rules
 
https://www.php-fig.org/psr/psr-12/ (7. Closures)
![image](https://user-images.githubusercontent.com/4511883/149280602-086952d1-3669-49bd-a18c-4fe4a5c83bae.png)
hence there should be space between `fn` and parenthesis

2022-01-13 06:58 UTC, a-laurowski requested changes
> sometimes we have `fn ($args)` and sometimes `fn($args)` please unify this.
> 
> What's more the arrow functions in many cases (if not all) don't contain returned type

I was looking for some PSR telling how to format the arrow function and i think we follow the closures rules
 
https://www.php-fig.org/psr/psr-12/ (7. Closures)
![image](https://user-images.githubusercontent.com/4511883/149280602-086952d1-3669-49bd-a18c-4fe4a5c83bae.png)
hence there should be space between `fn` and parenthesis

2022-01-19 11:02 UTC, a-laurowski approved these changes

2022-01-24 11:27 UTC, merged